#!/bin/sh

if git diff --cached --name-only | grep -q "services/admin/frontend/next-env.d.ts"; then
    echo "Error: services/admin/frontend/next-env.d.ts is read-only, changes are not allowed" >&2
    exit 1
fi

if git diff --cached --name-only | grep -q "services/admin/frontend/tsconfig.json"; then
    echo "Error: services/admin/frontend/tsconfig.json is read-only, changes are not allowed" >&2
    exit 1
fi

if git rev-parse --verify HEAD >/dev/null 2>&1
then
        against=HEAD
else
        # Initial commit: diff against an empty tree object
        against=$(git hash-object -t tree /dev/null)
fi

# If you want to allow non-ASCII filenames set this variable to true.
allownonascii=$(git config --type=bool hooks.allownonascii)

# Redirect output to stderr.
exec 1>&2

# Cross platform projects tend to avoid non-ASCII filenames; prevent
# them from being added to the repository. We exploit the fact that the
# printable range starts at the space character and ends with tilde.
if [ "$allownonascii" != "true" ] &&
        # Note that the use of brackets around a tr range is ok here, (it's
        # even required, for portability to Solaris 10's /usr/bin/tr), since
        # the square bracket bytes happen to fall in the designated range.
        # shellcheck disable=SC2046
        test $(git diff --cached --name-only --diff-filter=A -z $against |
          LC_ALL=C tr -d '[ -~]\0' | wc -c) != 0
then
        cat <<\EOF
Error: Attempt to add a non-ASCII file name.

This can cause problems if you want to work with people on other platforms.

To be portable it is advisable to rename the file.

If you know what you are doing you can disable this check using:

  git config hooks.allownonascii true
EOF
        exit 1
fi

# If there are whitespace errors, print the offending file names and fail.
# shellcheck disable=SC2093
exec git diff-index --check --cached $against --

# Run golangci-lint on staged Go files before allowing the commit.

STAGED=$(git diff --cached --name-only --diff-filter=ACM | grep '\.go$')
if [ -z "$STAGED" ]; then
  exit 0
fi

golangci-lint run services/admin/backend/...
golangci-lint run services/operational/backend/...