// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v4.25.3
// source: admin/internal/v1/internal.proto

package adminpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AdminInternal_Login_FullMethodName      = "/admin.internal.v1.AdminInternal/Login"
	AdminInternal_GoogleAuth_FullMethodName = "/admin.internal.v1.AdminInternal/GoogleAuth"
	AdminInternal_GetUser_FullMethodName    = "/admin.internal.v1.AdminInternal/GetUser"
)

// AdminInternalClient is the client API for AdminInternal service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AdminInternal is the service-to-service gRPC API exposed by the admin
// backend. Callers authenticate via the "x-service-key" metadata entry,
// validated by a server-side interceptor before any method runs.
//
// When SERVICE_API_KEY is unset, main.go skips starting the gRPC server
// entirely — callers get a connection-refused error rather than an auth error.
type AdminInternalClient interface {
	// Login validates email + password and returns the slim user DTO.
	// Returns UNAUTHENTICATED for every failure mode (unknown user, no password
	// set, wrong password) to avoid user enumeration — same posture as the
	// public login endpoint.
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*UserDTO, error)
	// GoogleAuth finds or creates a user from pre-verified Google ID token
	// claims. The caller (operational backend) has already validated the Google
	// ID token and forwards the three trustworthy claims.
	GoogleAuth(ctx context.Context, in *GoogleAuthRequest, opts ...grpc.CallOption) (*UserDTO, error)
	// GetUser returns the slim user DTO for the given public UUID.
	// Returns NOT_FOUND when no user exists for the UUID.
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*UserDTO, error)
}

type adminInternalClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminInternalClient(cc grpc.ClientConnInterface) AdminInternalClient {
	return &adminInternalClient{cc}
}

func (c *adminInternalClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*UserDTO, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserDTO)
	err := c.cc.Invoke(ctx, AdminInternal_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminInternalClient) GoogleAuth(ctx context.Context, in *GoogleAuthRequest, opts ...grpc.CallOption) (*UserDTO, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserDTO)
	err := c.cc.Invoke(ctx, AdminInternal_GoogleAuth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminInternalClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*UserDTO, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserDTO)
	err := c.cc.Invoke(ctx, AdminInternal_GetUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminInternalServer is the server API for AdminInternal service.
// All implementations must embed UnimplementedAdminInternalServer
// for forward compatibility.
//
// AdminInternal is the service-to-service gRPC API exposed by the admin
// backend. Callers authenticate via the "x-service-key" metadata entry,
// validated by a server-side interceptor before any method runs.
//
// When SERVICE_API_KEY is unset, main.go skips starting the gRPC server
// entirely — callers get a connection-refused error rather than an auth error.
type AdminInternalServer interface {
	// Login validates email + password and returns the slim user DTO.
	// Returns UNAUTHENTICATED for every failure mode (unknown user, no password
	// set, wrong password) to avoid user enumeration — same posture as the
	// public login endpoint.
	Login(context.Context, *LoginRequest) (*UserDTO, error)
	// GoogleAuth finds or creates a user from pre-verified Google ID token
	// claims. The caller (operational backend) has already validated the Google
	// ID token and forwards the three trustworthy claims.
	GoogleAuth(context.Context, *GoogleAuthRequest) (*UserDTO, error)
	// GetUser returns the slim user DTO for the given public UUID.
	// Returns NOT_FOUND when no user exists for the UUID.
	GetUser(context.Context, *GetUserRequest) (*UserDTO, error)
	mustEmbedUnimplementedAdminInternalServer()
}

// UnimplementedAdminInternalServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAdminInternalServer struct{}

func (UnimplementedAdminInternalServer) Login(context.Context, *LoginRequest) (*UserDTO, error) {
	return nil, status.Error(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedAdminInternalServer) GoogleAuth(context.Context, *GoogleAuthRequest) (*UserDTO, error) {
	return nil, status.Error(codes.Unimplemented, "method GoogleAuth not implemented")
}
func (UnimplementedAdminInternalServer) GetUser(context.Context, *GetUserRequest) (*UserDTO, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUser not implemented")
}
func (UnimplementedAdminInternalServer) mustEmbedUnimplementedAdminInternalServer() {}
func (UnimplementedAdminInternalServer) testEmbeddedByValue()                       {}

// UnsafeAdminInternalServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminInternalServer will
// result in compilation errors.
type UnsafeAdminInternalServer interface {
	mustEmbedUnimplementedAdminInternalServer()
}

func RegisterAdminInternalServer(s grpc.ServiceRegistrar, srv AdminInternalServer) {
	// If the following call panics, it indicates UnimplementedAdminInternalServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AdminInternal_ServiceDesc, srv)
}

func _AdminInternal_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminInternalServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminInternal_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminInternalServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminInternal_GoogleAuth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GoogleAuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminInternalServer).GoogleAuth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminInternal_GoogleAuth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminInternalServer).GoogleAuth(ctx, req.(*GoogleAuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminInternal_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminInternalServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminInternal_GetUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminInternalServer).GetUser(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AdminInternal_ServiceDesc is the grpc.ServiceDesc for AdminInternal service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdminInternal_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "admin.internal.v1.AdminInternal",
	HandlerType: (*AdminInternalServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _AdminInternal_Login_Handler,
		},
		{
			MethodName: "GoogleAuth",
			Handler:    _AdminInternal_GoogleAuth_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _AdminInternal_GetUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "admin/internal/v1/internal.proto",
}
