// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: admin/internal/v1/internal.proto

package adminpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_admin_internal_v1_internal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_internal_v1_internal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_admin_internal_v1_internal_proto_rawDescGZIP(), []int{0}
}

func (x *LoginRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type GoogleAuthRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// google_sub is the "sub" claim from the verified Google ID token.
	GoogleSub     string `protobuf:"bytes,1,opt,name=google_sub,json=googleSub,proto3" json:"google_sub,omitempty"`
	Email         string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Name          string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoogleAuthRequest) Reset() {
	*x = GoogleAuthRequest{}
	mi := &file_admin_internal_v1_internal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoogleAuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoogleAuthRequest) ProtoMessage() {}

func (x *GoogleAuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_internal_v1_internal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoogleAuthRequest.ProtoReflect.Descriptor instead.
func (*GoogleAuthRequest) Descriptor() ([]byte, []int) {
	return file_admin_internal_v1_internal_proto_rawDescGZIP(), []int{1}
}

func (x *GoogleAuthRequest) GetGoogleSub() string {
	if x != nil {
		return x.GoogleSub
	}
	return ""
}

func (x *GoogleAuthRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *GoogleAuthRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserUuid      string                 `protobuf:"bytes,1,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_admin_internal_v1_internal_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_internal_v1_internal_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_admin_internal_v1_internal_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserRequest) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

// UserDTO is the slim payload returned by every AdminInternal method.
// Sensitive columns (id, password_hash, totp_secret, google_id) are
// intentionally absent so callers can display the user and decide on next
// steps without holding identity secrets.
type UserDTO struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Uuid  string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Email string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Name  string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// role is empty when the user has no system-level role (root / system).
	Role          string `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	MfaEnabled    bool   `protobuf:"varint,5,opt,name=mfa_enabled,json=mfaEnabled,proto3" json:"mfa_enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserDTO) Reset() {
	*x = UserDTO{}
	mi := &file_admin_internal_v1_internal_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDTO) ProtoMessage() {}

func (x *UserDTO) ProtoReflect() protoreflect.Message {
	mi := &file_admin_internal_v1_internal_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDTO.ProtoReflect.Descriptor instead.
func (*UserDTO) Descriptor() ([]byte, []int) {
	return file_admin_internal_v1_internal_proto_rawDescGZIP(), []int{3}
}

func (x *UserDTO) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *UserDTO) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserDTO) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserDTO) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *UserDTO) GetMfaEnabled() bool {
	if x != nil {
		return x.MfaEnabled
	}
	return false
}

var File_admin_internal_v1_internal_proto protoreflect.FileDescriptor

const file_admin_internal_v1_internal_proto_rawDesc = "" +
	"\n" +
	" admin/internal/v1/internal.proto\x12\x11admin.internal.v1\"@\n" +
	"\fLoginRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\\\n" +
	"\x11GoogleAuthRequest\x12\x1d\n" +
	"\n" +
	"google_sub\x18\x01 \x01(\tR\tgoogleSub\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"-\n" +
	"\x0eGetUserRequest\x12\x1b\n" +
	"\tuser_uuid\x18\x01 \x01(\tR\buserUuid\"|\n" +
	"\aUserDTO\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\x12\x1f\n" +
	"\vmfa_enabled\x18\x05 \x01(\bR\n" +
	"mfaEnabled2\xef\x01\n" +
	"\rAdminInternal\x12D\n" +
	"\x05Login\x12\x1f.admin.internal.v1.LoginRequest\x1a\x1a.admin.internal.v1.UserDTO\x12N\n" +
	"\n" +
	"GoogleAuth\x12$.admin.internal.v1.GoogleAuthRequest\x1a\x1a.admin.internal.v1.UserDTO\x12H\n" +
	"\aGetUser\x12!.admin.internal.v1.GetUserRequest\x1a\x1a.admin.internal.v1.UserDTOB<Z:charity-chest/services/admin/backend/internal/grpc/adminpbb\x06proto3"

var (
	file_admin_internal_v1_internal_proto_rawDescOnce sync.Once
	file_admin_internal_v1_internal_proto_rawDescData []byte
)

func file_admin_internal_v1_internal_proto_rawDescGZIP() []byte {
	file_admin_internal_v1_internal_proto_rawDescOnce.Do(func() {
		file_admin_internal_v1_internal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_admin_internal_v1_internal_proto_rawDesc), len(file_admin_internal_v1_internal_proto_rawDesc)))
	})
	return file_admin_internal_v1_internal_proto_rawDescData
}

var file_admin_internal_v1_internal_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_admin_internal_v1_internal_proto_goTypes = []any{
	(*LoginRequest)(nil),      // 0: admin.internal.v1.LoginRequest
	(*GoogleAuthRequest)(nil), // 1: admin.internal.v1.GoogleAuthRequest
	(*GetUserRequest)(nil),    // 2: admin.internal.v1.GetUserRequest
	(*UserDTO)(nil),           // 3: admin.internal.v1.UserDTO
}
var file_admin_internal_v1_internal_proto_depIdxs = []int32{
	0, // 0: admin.internal.v1.AdminInternal.Login:input_type -> admin.internal.v1.LoginRequest
	1, // 1: admin.internal.v1.AdminInternal.GoogleAuth:input_type -> admin.internal.v1.GoogleAuthRequest
	2, // 2: admin.internal.v1.AdminInternal.GetUser:input_type -> admin.internal.v1.GetUserRequest
	3, // 3: admin.internal.v1.AdminInternal.Login:output_type -> admin.internal.v1.UserDTO
	3, // 4: admin.internal.v1.AdminInternal.GoogleAuth:output_type -> admin.internal.v1.UserDTO
	3, // 5: admin.internal.v1.AdminInternal.GetUser:output_type -> admin.internal.v1.UserDTO
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_admin_internal_v1_internal_proto_init() }
func file_admin_internal_v1_internal_proto_init() {
	if File_admin_internal_v1_internal_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_admin_internal_v1_internal_proto_rawDesc), len(file_admin_internal_v1_internal_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_admin_internal_v1_internal_proto_goTypes,
		DependencyIndexes: file_admin_internal_v1_internal_proto_depIdxs,
		MessageInfos:      file_admin_internal_v1_internal_proto_msgTypes,
	}.Build()
	File_admin_internal_v1_internal_proto = out.File
	file_admin_internal_v1_internal_proto_goTypes = nil
	file_admin_internal_v1_internal_proto_depIdxs = nil
}
